In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [19]:
df1 = pd.read_csv('C://Users//user//Desktop//major_project//keystroke-dynamics-datagen-master//Keystroke-Dynamics-Using-LSTMs-master//Keystroke-Dynamics-Using-LSTMs-master/shiva_appended.csv')
df2= pd.read_csv('C://Users//user//Desktop//major_project//keystroke-dynamics-datagen-master//Keystroke-Dynamics-Using-LSTMs-master//Keystroke-Dynamics-Using-LSTMs-master/shiva_fraud_appended.csv')

In [20]:
df1.shape

(1000, 32)

In [21]:
df2.shape

(400, 32)

In [22]:
df1['output']=1

In [23]:
df1


Name         a         b         c         d         e         f  \
0    shiva  0.149134  0.095284  0.244418  0.078049  0.186720  0.264769   
1    shiva  0.120761  0.070547  0.191308  0.088534  0.160494  0.249028   
2    shiva  0.140864  0.054410  0.195274  0.076005  0.156120  0.232125   
3    shiva  0.129242  0.105580  0.234822  0.078046  0.166502  0.244548   
4    shiva  0.118013  0.092016  0.210029  0.061421  0.192829  0.254250   
..     ...       ...       ...       ...       ...       ...       ...   
995  shiva  0.147444  0.129234  0.276678  0.087070  0.186962  0.274032   
996  shiva  0.148127  0.045824  0.193951  0.079270  0.158741  0.238011   
997  shiva  0.129242  0.105580  0.234822  0.078046  0.166502  0.244548   
998  shiva  0.151231  0.069955  0.221186  0.062336  0.156849  0.219185   
999  shiva  0.140886  0.101096  0.241982  0.091312  0.182766  0.274078   

            g         h         i  ...  Previous_latitude  Previous_longitude  \
0    0.111879  0.155903  0.267782  ...          12.914142           74.855957   
1    0.094145  0.191520  0.285665  ...          12.914142           74.855957   
2    0.090494  0.174344  0.264838  ...          12.914142           74.855957   
3    0.114891  0.166035  0.280926  ...          12.914142           74.855957   
4    0.101509  0.200519  0.302028  ...          12.914142           74.855957   
..        ...       ...       ...  ...                ...                 ...   
995  0.102599  0.176595  0.279194  ...          13.082680           80.270721   
996  0.086865  0.227050  0.313915  ...          17.385044           78.486671   
997  0.114891  0.166035  0.280926  ...          12.914142           74.855957   
998  0.087188  0.181895  0.269083  ...          17.385044           78.486671   
999  0.098820  0.189565  0.288385  ...          13.082680           80.270721   

     Previous_latitude.1  Present_longitude  pressure_s  pressure_h  \
0              12.914142          74.855957       801.0       796.0   
1              12.971599          77.594566       939.0       719.0   
2              17.385044          78.486671       899.0       353.0   
3              42.331429         -83.045753       913.0       593.0   
4              36.778259        -119.417931       949.0       603.0   
..                   ...                ...         ...         ...   
995            34.083672          74.797279       886.0       573.0   
996            28.704060          77.102493       961.0       782.0   
997            42.331429         -83.045753       954.0       784.0   
998            36.778259        -119.417931       888.0       682.0   
999            12.971599          77.594566       779.0       447.0   

     pressure_i  pressure_v  pressure_a  output  
0           368         690       798.0       1  
1           928         831       409.0       1  
2           956         907       624.0       1  
3           886         931       934.0       1  
4           905         925       911.0       1  
..          ...         ...         ...     ...  
995         922         902       790.0       1  
996         928         960       850.0       1  
997         862         894       960.0       1  
998         944         804       885.0       1  
999         926         946       756.0       1  

[1000 rows x 33 columns]

In [24]:
df2['output']=0

In [25]:
df2

Name         a         b         c         d         e         f  \
0    fshiva  0.165581  0.078276  0.243857  0.146824  0.102373  0.249197   
1    fshiva  0.140557  0.508879  0.649436  0.083952  0.403836  0.487788   
2    fshiva  0.156596  0.403169  0.559765  0.073859  0.490833  0.564692   
3    fshiva  0.143176  0.648242  0.791418  0.066525  0.493274  0.559799   
4    fshiva  0.139343  0.355161  0.494504  0.070443  0.383469  0.453912   
..      ...       ...       ...       ...       ...       ...       ...   
395  fshiva  0.154248  0.128296  0.282544  0.090151  0.137850  0.228001   
396  fshiva  0.115292  0.207154  0.322446  0.063008  0.302537  0.365545   
397  fshiva  0.161652  0.187839  0.349491  0.071358  0.302354  0.373712   
398  fshiva  0.113651  0.260368  0.374019  0.058543  1.161646  1.220189   
399  fshiva  0.141645  0.162381  0.304026  0.072753  0.246706  0.319459   

            g         h         i  ...  Previous_latitude  Previous_longitude  \
0    0.139691  1.539032  1.678723  ...          12.914142           74.855957   
1    0.088415  0.641942  0.730357  ...          12.914142           74.855957   
2    0.064429  0.453682  0.518111  ...          12.914142           74.855957   
3    0.065243  0.667238  0.732481  ...          12.914142           74.855957   
4    0.071446  0.806393  0.877839  ...          12.914142           74.855957   
..        ...       ...       ...  ...                ...                 ...   
395  0.092422  0.233860  0.326282  ...          36.778259         -119.417931   
396  0.081431  0.340915  0.422346  ...          28.704060           77.102493   
397  0.082195  0.335884  0.418079  ...          12.971599           77.594566   
398  0.062964  0.363273  0.426237  ...          28.704060           77.102493   
399  0.068451  0.300868  0.369319  ...          34.083672           74.797279   

     Previous_latitude.1  Present_longitude  pressure_s  pressure_h  \
0              12.914142          74.855957       886.0       813.0   
1              12.971599          77.594566       966.0       698.0   
2              17.385044          78.486671       694.0       748.0   
3              42.331429         -83.045753       895.0       942.0   
4              36.778259        -119.417931       491.0       493.0   
..                   ...                ...         ...         ...   
395            12.914142          74.855957       829.0       860.0   
396            12.914142          74.855957       731.0       471.0   
397            12.971599          77.594566       394.5       805.0   
398            19.075983          72.877655       408.5       831.0   
399            28.704060          77.102493       722.0       775.0   

     pressure_i  pressure_v  pressure_a  output  
0         899.0       101.0       815.0       0  
1         897.5       225.0       351.0       0  
2         661.0       446.0       620.0       0  
3         877.0       421.0       865.0       0  
4         922.0       425.0       641.0       0  
..          ...         ...         ...     ...  
395       888.0       536.0       790.0       0  
396       183.0       759.0       670.0       0  
397       615.0       101.0       371.0       0  
398       897.0       732.0       631.0       0  
399       371.0       357.0       867.0       0  

[400 rows x 33 columns]

In [26]:
df_train=pd.concat([df1, df2], axis=0)

In [27]:
df_train

Name         a         b         c         d         e         f  \
0     shiva  0.149134  0.095284  0.244418  0.078049  0.186720  0.264769   
1     shiva  0.120761  0.070547  0.191308  0.088534  0.160494  0.249028   
2     shiva  0.140864  0.054410  0.195274  0.076005  0.156120  0.232125   
3     shiva  0.129242  0.105580  0.234822  0.078046  0.166502  0.244548   
4     shiva  0.118013  0.092016  0.210029  0.061421  0.192829  0.254250   
..      ...       ...       ...       ...       ...       ...       ...   
395  fshiva  0.154248  0.128296  0.282544  0.090151  0.137850  0.228001   
396  fshiva  0.115292  0.207154  0.322446  0.063008  0.302537  0.365545   
397  fshiva  0.161652  0.187839  0.349491  0.071358  0.302354  0.373712   
398  fshiva  0.113651  0.260368  0.374019  0.058543  1.161646  1.220189   
399  fshiva  0.141645  0.162381  0.304026  0.072753  0.246706  0.319459   

            g         h         i  ...  Previous_latitude  Previous_longitude  \
0    0.111879  0.155903  0.267782  ...          12.914142           74.855957   
1    0.094145  0.191520  0.285665  ...          12.914142           74.855957   
2    0.090494  0.174344  0.264838  ...          12.914142           74.855957   
3    0.114891  0.166035  0.280926  ...          12.914142           74.855957   
4    0.101509  0.200519  0.302028  ...          12.914142           74.855957   
..        ...       ...       ...  ...                ...                 ...   
395  0.092422  0.233860  0.326282  ...          36.778259         -119.417931   
396  0.081431  0.340915  0.422346  ...          28.704060           77.102493   
397  0.082195  0.335884  0.418079  ...          12.971599           77.594566   
398  0.062964  0.363273  0.426237  ...          28.704060           77.102493   
399  0.068451  0.300868  0.369319  ...          34.083672           74.797279   

     Previous_latitude.1  Present_longitude  pressure_s  pressure_h  \
0              12.914142          74.855957       801.0       796.0   
1              12.971599          77.594566       939.0       719.0   
2              17.385044          78.486671       899.0       353.0   
3              42.331429         -83.045753       913.0       593.0   
4              36.778259        -119.417931       949.0       603.0   
..                   ...                ...         ...         ...   
395            12.914142          74.855957       829.0       860.0   
396            12.914142          74.855957       731.0       471.0   
397            12.971599          77.594566       394.5       805.0   
398            19.075983          72.877655       408.5       831.0   
399            28.704060          77.102493       722.0       775.0   

     pressure_i  pressure_v  pressure_a  output  
0         368.0       690.0       798.0       1  
1         928.0       831.0       409.0       1  
2         956.0       907.0       624.0       1  
3         886.0       931.0       934.0       1  
4         905.0       925.0       911.0       1  
..          ...         ...         ...     ...  
395       888.0       536.0       790.0       0  
396       183.0       759.0       670.0       0  
397       615.0       101.0       371.0       0  
398       897.0       732.0       631.0       0  
399       371.0       357.0       867.0       0  

[1400 rows x 33 columns]

In [28]:
from sklearn.utils import shuffle
df = shuffle(df_train)
df

Name         a         b         c         d         e         f  \
383  fshiva  0.167163  0.480048  0.647211  0.065894  0.282048  0.347942   
69    shiva  0.134011  0.109762  0.243773  0.075586  0.183922  0.259508   
552   shiva  0.124016  0.096282  0.220298  0.083195  0.165626  0.248821   
815   shiva  0.148794  0.129707  0.278501  0.085575  0.162796  0.248371   
323  fshiva  0.137905  0.210750  0.348655  0.064556  0.252676  0.317232   
..      ...       ...       ...       ...       ...       ...       ...   
548   shiva  0.116510  0.153594  0.270104  0.101442  0.172223  0.273665   
637   shiva  0.126698  0.089803  0.216501  0.081081  0.172020  0.253101   
666   shiva  0.132393  0.122808  0.255201  0.079592  0.169884  0.249476   
568   shiva  0.127057  0.096132  0.223189  0.086627  0.165829  0.252456   
686   shiva  0.151193  0.113291  0.264484  0.076979  0.171117  0.248096   

            g         h         i  ...  Previous_latitude  Previous_longitude  \
383  0.077144  3.514770  3.591914  ...          17.385044           78.486671   
69   0.100524  0.154683  0.255207  ...          13.082680           80.270721   
552  0.091296  0.182363  0.273659  ...          12.971599           77.594566   
815  0.096657  0.195293  0.291950  ...          28.704060           77.102493   
323  0.059266  0.361556  0.420822  ...          36.778259         -119.417931   
..        ...       ...       ...  ...                ...                 ...   
548  0.095774  0.196121  0.291895  ...          12.971599           77.594566   
637  0.084699  0.170917  0.255616  ...          36.778259         -119.417931   
666  0.095643  0.186131  0.281774  ...          19.075983           72.877655   
568  0.111750  0.168374  0.280124  ...          12.971599           77.594566   
686  0.102199  0.176066  0.278265  ...          28.704060           77.102493   

     Previous_latitude.1  Present_longitude  pressure_s  pressure_h  \
383            13.082680          80.270721       431.0       806.0   
69            -33.868820         151.209290       866.0       387.0   
552            28.704060          77.102493       920.0       649.0   
815            36.778259        -119.417931       953.0       516.0   
323            42.331429         -83.045753       729.0       462.0   
..                   ...                ...         ...         ...   
548            19.075983          72.877655       921.0       443.0   
637           -33.868820         151.209290       596.0       653.0   
666            28.704060          77.102493       934.0       589.0   
568            13.082680          80.270721       946.0       633.0   
686            17.385044          78.486671       931.0       675.0   

     pressure_i  pressure_v  pressure_a  output  
383       899.0       705.0       707.0       0  
69        849.0       696.0       810.0       1  
552       886.0       921.0       830.0       1  
815       861.0       899.0       909.0       1  
323       897.0       390.0       748.0       0  
..          ...         ...         ...     ...  
548       562.0       935.0       717.0       1  
637       778.0       955.0       728.0       1  
666       920.0       550.0       760.0       1  
568       920.0       919.0       867.0       1  
686       947.0       928.0       885.0       1  

[1400 rows x 33 columns]

In [29]:
df1=df.iloc[:,1:20]
df2=df.iloc[:,23:]
df=pd.concat([df1,df2],axis=1)
array = df.values
X = array[:,0:21]
Y = array[:,-1]

In [30]:
X.shape

(1400, 21)

In [31]:
Y

array([0., 1., 1., ..., 1., 1., 1.])

In [32]:
# Load libraries
import pandas
from pandas.plotting import scatter_matrix
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [33]:
validation_size = 0.20
seed = 7
X_train, X_validation, Y_train, Y_validation = model_selection.train_test_split(X, Y, test_size=validation_size, random_state=seed)

In [34]:
X_train.shape

(1120, 21)

In [35]:
Y_train.shape

(1120,)

In [36]:
X_train

array([[ 1.19601965e-01,  1.01691008e-01,  2.21292973e-01, ...,
         0.00000000e+00, -3.38688200e+01,  1.51209290e+02],
       [ 1.16509914e-01,  1.53594017e-01,  2.70103931e-01, ...,
         1.00000000e+00,  1.29715990e+01,  7.75945660e+01],
       [ 1.57474995e-01,  1.04674816e-01,  2.62149811e-01, ...,
         1.00000000e+00,  3.67782590e+01, -1.19417931e+02],
       ...,
       [ 1.21705055e-01,  1.37157917e-01,  2.58862972e-01, ...,
         1.00000000e+00,  1.29715990e+01,  7.75945660e+01],
       [ 1.27285957e-01,  9.29039955e-01,  1.05632591e+00, ...,
         1.00000000e+00,  1.73850440e+01,  7.84866710e+01],
       [ 1.31767035e-01,  8.53610040e-02,  2.17128038e-01, ...,
         0.00000000e+00,  1.90759830e+01,  7.28776550e+01]])

In [37]:
from sklearn.linear_model import LogisticRegression
logisticRegr = LogisticRegression()
logisticRegr.fit(X_train, Y_train)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [305]:
y_pred=logisticRegr.predict(X_validation)

In [306]:
from sklearn import metrics 
print("logistic regression model accuracy:", metrics.accuracy_score(Y_validation, y_pred))

logistic regression model accuracy: 0.9857142857142858


In [52]:
from sklearn import svm
svc = svm.SVC(kernel='linear')
svc.fit(X_train,Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [53]:
y_pred=svc.predict(X_validation)

In [54]:
from sklearn import metrics 
print("svm model accuracy:", metrics.accuracy_score(y_pred, Y_validation))

svm model accuracy: 0.8607142857142858


In [55]:
from sklearn.model_selection import cross_val_score
clf =  LogisticRegression()
scores = cross_val_score(clf, X, Y, cv=4)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [56]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.96 (+/- 0.04)


In [57]:
from sklearn.model_selection import cross_val_score
clf = svm.SVC(kernel='linear', C=1)
scores1 = cross_val_score(clf, X, Y, cv=5)
scores1

array([0.85      , 0.86785714, 0.87142857, 0.83214286, 0.85357143])

In [58]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores1.mean(), scores1.std() * 2))

Accuracy: 0.86 (+/- 0.03)


In [237]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
k_range=range(1,3)
scores={}
scores_list=[]
for k in k_range:
    knn=KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train,Y_train)
    y_pred=knn.predict(X_validation)
    scores[k]=metrics.accuracy_score(Y_validation,y_pred)
    scores_list.append(metrics.accuracy_score(Y_validation,y_pred))

In [238]:
scores_list

[1.0, 1.0]

In [61]:
# Import the model we are using
from sklearn.ensemble import RandomForestRegressor
# Instantiate model with 1000 decision trees
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)
# Train the model on training data
rf.fit(X_train, Y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=1000,
                      n_jobs=None, oob_score=False, random_state=42, verbose=0,
                      warm_start=False)

In [63]:
predictions = rf.predict(X_validation)
# Calculate the absolute errors
errors = abs(predictions - Y_validation)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 0.0 degrees.


In [64]:
predictions

array([0.   , 0.075, 1.   , 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 0.   , 0.001, 0.   , 0.   , 0.   , 1.   , 0.057,
       1.   , 1.   , 1.   , 0.   , 1.   , 1.   , 0.064, 1.   , 1.   ,
       1.   , 0.   , 1.   , 1.   , 0.009, 1.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 0.   , 1.   , 1.   , 1.   , 0.006, 1.   , 1.   ,
       1.   , 1.   , 1.   , 0.   , 1.   , 0.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 1.   , 0.064, 1.   , 1.   , 0.064, 0.022, 1.   ,
       1.   , 0.057, 1.   , 1.   , 1.   , 0.   , 1.   , 0.009, 1.   ,
       1.   , 1.   , 1.   , 0.   , 0.   , 0.   , 1.   , 1.   , 1.   ,
       1.   , 0.   , 1.   , 1.   , 0.049, 0.009, 1.   , 0.   , 0.   ,
       0.   , 1.   , 1.   , 1.   , 1.   , 0.   , 0.   , 1.   , 0.   ,
       1.   , 0.   , 1.   , 1.   , 1.   , 0.   , 1.   , 0.002, 1.   ,
       1.   , 1.   , 0.   , 1.   , 1.   , 0.   , 1.   , 1.   , 1.   ,
       1.   , 1.   , 0.   , 0.   , 1.   , 0.   , 1.   , 1.   , 1.   ,
       1.   , 1.   ,

In [267]:
from sklearn.model_selection import cross_val_score
import numpy as np
#create a new KNN model
knn_cv = KNeighborsClassifier(n_neighbors=3)
#train model with cv of 5 
cv_scores = cross_val_score(knn_cv, X, Y, cv=5)
#print each cv score (accuracy) and average them
print(cv_scores)
#print(‘cv_scores mean:{}’.format(np.mean(cv_scores)))

[0.975      0.98928571 0.975      0.97857143 0.97857143]


In [268]:
print("Accuracy: %0.2f (+/- %0.2f)" % (cv_scores.mean(), cv_scores.std() * 2))

Accuracy: 0.98 (+/- 0.01)


In [38]:
from sklearn.neighbors import KNeighborsClassifier 
knn = KNeighborsClassifier(n_neighbors=3) 
knn.fit(X_train, Y_train) 
y_pred = knn.predict(X_validation) 
# comparing actual response values (y_test) with predicted response values (y_pred) 
from sklearn import metrics 
print("kNN model accuracy:", metrics.accuracy_score(Y_validation, y_pred))

kNN model accuracy: 0.9785714285714285


In [45]:
Y = Y.astype(int)

In [55]:
X_train.shape[1] = 

TypeError: 'tuple' object does not support item assignment

In [57]:
import mlxtend
import matplotlib.pyplot as plt
from sklearn import datasets, neighbors
from mlxtend.plotting import plot_decision_regions
plot_decision_regions(X, Y, clf=knn,feature_index=[0,2],                        #these one will be plotted  
              filler_feature_values={1: value, 3:value},  #these will be ignored
              filler_feature_ranges={1: width, 3: width})
# Adding axes annotations
plt.xlabel('X')
plt.ylabel('Y')
plt.title('Knn with K='+ str(k))
plt.show()

NameError: name 'value' is not defined